fix jest transpiling all node modules, make tests fast again (#78)
the previous regexp is bugged, it requires '//' in the filename !!
As a result, all the files in node_modules don't pass the regex
so nothing is ignored => everything is transformed

jest caches this in /tmp/jest_* so rerunning tests is fast, but
the first time jest takes minutes to transform everything

also the previous config was incomplete for moduleNameMapper but this was not
visible because it transformed everything anyway:
    Jest encountered an unexpected token
    Details:
       /node_modules/ag-grid-community/styles/ag-grid.css:1
       ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){.ag-icon {
                                                                                         ^
       SyntaxError: Unexpected token '.'

    Details:
       /node_modules/react-dnd/dist/index.js:1
       ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './core/index.js';
                                                                                         ^^^^^^
    SyntaxError: Unexpected token 'export'